export interface AcronymDef {
  term: string;
  full: string;
  short: string;
  aliases?: string[];
}

export const ACRONYMS: AcronymDef[] = [
  { term: 'AAA', full: 'Authentication, Authorization, Accounting', short: 'Identity framework: who you are, what you can do, and what gets logged.' },
  { term: 'AAAA', full: 'IPv6 Address Record', short: 'DNS record that maps a hostname to an IPv6 address.' },
  { term: 'ACL', full: 'Access Control List', short: 'Rule list that permits or denies traffic.' },
  { term: 'AD', full: 'Active Directory', short: 'Microsoft directory service for users, devices, and authentication.' },
  { term: 'AP', full: 'Access Point', short: 'Wireless device that connects Wi-Fi clients to the wired network.' },
  { term: 'APIPA', full: 'Automatic Private IP Addressing', short: '169.254.x.x self-assigned address when DHCP fails.' },
  { term: 'ARP', full: 'Address Resolution Protocol', short: 'Maps an IPv4 address to a MAC address on the local network.' },
  { term: 'BGP', full: 'Border Gateway Protocol', short: 'Routing protocol used between autonomous systems on the internet.' },
  { term: 'BPDU', full: 'Bridge Protocol Data Unit', short: 'STP message switches use to detect loops and elect paths.' },
  { term: 'CA', full: 'Certificate Authority', short: 'Trusted issuer that signs digital certificates.' },
  { term: 'CAM', full: 'Content Addressable Memory', short: 'Switch table that maps MAC addresses to ports.' },
  { term: 'CNAME', full: 'Canonical Name Record', short: 'DNS alias record that points one name to another name.' },
  { term: 'CRC', full: 'Cyclic Redundancy Check', short: 'Error check used to detect corrupted frames.' },
  { term: 'DAI', full: 'Dynamic ARP Inspection', short: 'Switch feature that blocks forged ARP replies.' },
  { term: 'DMZ', full: 'Demilitarized Zone', short: 'Network segment for public-facing services separated from internal hosts.' },
  { term: 'CIA', full: 'Confidentiality, Integrity, Availability', short: 'Security model for secrecy, trustworthiness, and uptime.' },
  { term: 'DHCP', full: 'Dynamic Host Configuration Protocol', short: 'Automatically gives clients IP settings like address, gateway, and DNS.' },
  { term: 'DNS', full: 'Domain Name System', short: 'Turns hostnames into IP addresses.' },
  { term: 'DNSSEC', full: 'Domain Name System Security Extensions', short: 'Adds signed DNS data so clients can validate responses.' },
  { term: 'DORA', full: 'Discover, Offer, Request, Acknowledge', short: 'The four-step DHCP lease process.' },
  { term: 'DSCP', full: 'Differentiated Services Code Point', short: 'QoS marking field used to classify traffic priority.' },
  { term: 'EAP', full: 'Extensible Authentication Protocol', short: 'Authentication framework often used with 802.1X.' },
  { term: 'EIGRP', full: 'Enhanced Interior Gateway Routing Protocol', short: 'Cisco interior routing protocol.' },
  { term: 'ESP', full: 'Encapsulating Security Payload', short: 'IPsec protocol that encrypts and authenticates VPN traffic.' },
  { term: 'FHRP', full: 'First Hop Redundancy Protocol', short: 'Lets routers share a virtual default gateway for failover.' },
  { term: 'FTP', full: 'File Transfer Protocol', short: 'Plain file transfer protocol that uses TCP 20 and 21.' },
  { term: 'GLBP', full: 'Gateway Load Balancing Protocol', short: 'Cisco FHRP that can load balance across multiple routers.' },
  { term: 'GRE', full: 'Generic Routing Encapsulation', short: 'Tunneling protocol that encapsulates packets, but does not encrypt by itself.' },
  { term: 'HSRP', full: 'Hot Standby Router Protocol', short: 'Cisco active and standby gateway redundancy protocol.' },
  { term: 'HTTP', full: 'Hypertext Transfer Protocol', short: 'Plain web traffic on TCP 80.' },
  { term: 'HTTPS', full: 'Hypertext Transfer Protocol Secure', short: 'Encrypted web traffic using TLS on TCP 443.' },
  { term: 'ICMP', full: 'Internet Control Message Protocol', short: 'Used by ping and network control messages.' },
  { term: 'IDS', full: 'Intrusion Detection System', short: 'Detects suspicious traffic and alerts, but does not block inline.' },
  { term: 'IGP', full: 'Interior Gateway Protocol', short: 'Routing protocol used inside one organization.' },
  { term: 'IETF', full: 'Internet Engineering Task Force', short: 'Standards body that publishes RFCs for internet protocols.' },
  { term: 'IKE', full: 'Internet Key Exchange', short: 'Negotiates security associations for IPsec VPNs.' },
  { term: 'IMAP', full: 'Internet Message Access Protocol', short: 'Accesses email while keeping it on the mail server.' },
  { term: 'IP', full: 'Internet Protocol', short: 'Logical addressing used to route packets between networks.' },
  { term: 'IPFIX', full: 'IP Flow Information Export', short: 'Flow export standard used to report traffic metadata.' },
  { term: 'IPS', full: 'Intrusion Prevention System', short: 'Sits inline and actively blocks malicious traffic.' },
  { term: 'ISP', full: 'Internet Service Provider', short: 'Company that provides internet connectivity.' },
  { term: 'LAN', full: 'Local Area Network', short: 'Network in a small area like a home, office, or building.' },
  { term: 'LACP', full: 'Link Aggregation Control Protocol', short: 'Combines multiple physical links into one logical bundle.' },
  { term: 'LDAP', full: 'Lightweight Directory Access Protocol', short: 'Queries directory services like Active Directory.' },
  { term: 'LTE', full: 'Long-Term Evolution', short: 'Cellular network technology often used as a WAN backup link.' },
  { term: 'MAC', full: 'Media Access Control', short: 'Layer 2 hardware address used for local delivery.' },
  { term: 'MTBF', full: 'Mean Time Between Failures', short: 'Average time a system runs before it fails.' },
  { term: 'MTTR', full: 'Mean Time To Repair', short: 'Average time needed to fix a failed system.' },
  { term: 'MTU', full: 'Maximum Transmission Unit', short: 'Largest frame or packet size allowed before fragmentation.' },
  { term: 'MPLS', full: 'Multiprotocol Label Switching', short: 'WAN technology that forwards traffic using labels instead of normal IP lookup.' },
  { term: 'MSS', full: 'Maximum Segment Size', short: 'Largest TCP payload size before headers.' },
  { term: 'MSTP', full: 'Multiple Spanning Tree Protocol', short: 'STP version that maps VLANs to multiple spanning tree instances.' },
  { term: 'NAT', full: 'Network Address Translation', short: 'Translates private addresses to public addresses.' },
  { term: 'NAT64', full: 'Network Address Translation 64', short: 'Translates IPv6 traffic so it can reach IPv4 services.' },
  { term: 'NGFW', full: 'Next-Generation Firewall', short: 'Firewall that understands apps, users, and deeper traffic context.' },
  { term: 'NIC', full: 'Network Interface Card', short: 'Network adapter that connects a device to the network.' },
  { term: 'NMS', full: 'Network Management System', short: 'Central platform used to monitor and manage network devices.' },
  { term: 'NTP', full: 'Network Time Protocol', short: 'Synchronizes device clocks across the network.' },
  { term: 'OFDMA', full: 'Orthogonal Frequency-Division Multiple Access', short: 'Wi-Fi 6 feature that helps serve many clients at once.' },
  { term: 'OSI', full: 'Open Systems Interconnection', short: 'Seven-layer model used to explain how networks communicate.' },
  { term: 'OSPF', full: 'Open Shortest Path First', short: 'Link-state interior routing protocol that uses cost.' },
  { term: 'OTDR', full: 'Optical Time-Domain Reflectometer', short: 'Fiber testing tool that finds distance to faults and breaks.' },
  { term: 'PAT', full: 'Port Address Translation', short: 'Many private devices share one public IP by using unique ports.' },
  { term: 'PBQ', full: 'Performance-Based Question', short: 'Hands-on exam question where you configure, sort, or troubleshoot.' },
  { term: 'PDU', full: 'Protocol Data Unit', short: 'Name for data at a given OSI layer, such as frame, packet, or segment.' },
  { term: 'PoE', full: 'Power over Ethernet', short: 'Carries data and electrical power on the same Ethernet cable.', aliases: ['POE'] },
  { term: 'POP3', full: 'Post Office Protocol version 3', short: 'Downloads email from a mail server to a local client.' },
  { term: 'PSK', full: 'Pre-Shared Key', short: 'One shared Wi-Fi password used by everyone on the network.' },
  { term: 'PTR', full: 'Pointer Record', short: 'DNS record used for reverse lookup from IP address to hostname.' },
  { term: 'QoS', full: 'Quality of Service', short: 'Prioritizes time-sensitive traffic like voice and video.', aliases: ['QOS'] },
  { term: 'RADIUS', full: 'Remote Authentication Dial-In User Service', short: 'AAA protocol commonly used for network access with 802.1X.' },
  { term: 'RBAC', full: 'Role-Based Access Control', short: 'Access model where permissions come from assigned roles.' },
  { term: 'RDP', full: 'Remote Desktop Protocol', short: 'Graphical remote access to a Windows machine on TCP 3389.' },
  { term: 'RF', full: 'Radio Frequency', short: 'Wireless signal energy used by Wi-Fi and other radio systems.' },
  { term: 'RFC', full: 'Request for Comments', short: 'Numbered internet standards documents published through the IETF.' },
  { term: 'RIP', full: 'Routing Information Protocol', short: 'Older distance-vector routing protocol that counts hops.' },
  { term: 'RPO', full: 'Recovery Point Objective', short: 'How much data loss is acceptable, measured in time.' },
  { term: 'RSTP', full: 'Rapid Spanning Tree Protocol', short: 'Faster version of STP for preventing Layer 2 loops.' },
  { term: 'RTO', full: 'Recovery Time Objective', short: 'How quickly service must be restored after an outage.' },
  { term: 'RTT', full: 'Round-Trip Time', short: 'Time for traffic to go to a destination and back.' },
  { term: 'SASE', full: 'Secure Access Service Edge', short: 'Cloud-delivered networking and security model.' },
  { term: 'SCP', full: 'Secure Copy Protocol', short: 'Encrypted file copy over SSH.' },
  { term: 'SD-WAN', full: 'Software-Defined Wide Area Network', short: 'Centrally steers WAN traffic across links like MPLS, broadband, and LTE.' },
  { term: 'SDN', full: 'Software-Defined Networking', short: 'Separates network control from forwarding so policy can be centrally managed.' },
  { term: 'SFTP', full: 'SSH File Transfer Protocol', short: 'Encrypted file transfer over SSH.' },
  { term: 'SLA', full: 'Service Level Agreement', short: 'Contracted promise for service quality, often uptime or response time.' },
  { term: 'SMB', full: 'Server Message Block', short: 'Windows file and printer sharing protocol on TCP 445.' },
  { term: 'SMTP', full: 'Simple Mail Transfer Protocol', short: 'Sends email between mail servers on TCP 25.' },
  { term: 'SNMP', full: 'Simple Network Management Protocol', short: 'Monitors and manages network devices.' },
  { term: 'SOA', full: 'Start of Authority', short: 'DNS record that defines authoritative zone information.' },
  { term: 'SPAN', full: 'Switched Port Analyzer', short: 'Cisco port mirroring feature used to copy traffic for analysis.' },
  { term: 'SPF', full: 'Sender Policy Framework', short: 'DNS-based email authentication record that lists allowed mail senders.' },
  { term: 'SSID', full: 'Service Set Identifier', short: 'The visible Wi-Fi network name.' },
  { term: 'SSH', full: 'Secure Shell', short: 'Encrypted remote command-line access on TCP 22.' },
  { term: 'STP', full: 'Spanning Tree Protocol', short: 'Prevents switching loops and broadcast storms.' },
  { term: 'SVI', full: 'Switched Virtual Interface', short: 'Layer 3 VLAN interface used for routing or switch management.' },
  { term: 'SYN', full: 'Synchronize', short: 'TCP flag used to start a connection during the three-way handshake.' },
  { term: 'TACACS+', full: 'Terminal Access Controller Access-Control System Plus', short: 'AAA protocol often used for network device administration.' },
  { term: 'TCP', full: 'Transmission Control Protocol', short: 'Reliable transport protocol with acknowledgments and retransmission.' },
  { term: 'TFTP', full: 'Trivial File Transfer Protocol', short: 'Simple file transfer protocol with no authentication on UDP 69.' },
  { term: 'TLS', full: 'Transport Layer Security', short: 'Encryption used to protect traffic like HTTPS.' },
  { term: 'TTL', full: 'Time To Live', short: 'IP field that decreases at each router hop to prevent endless loops.' },
  { term: 'TXT', full: 'Text Record', short: 'DNS record that stores text values such as SPF or verification data.' },
  { term: 'UDP', full: 'User Datagram Protocol', short: 'Fast connectionless transport protocol with no retransmission.' },
  { term: 'UTP', full: 'Unshielded Twisted Pair', short: 'Common copper Ethernet cable without extra shielding.' },
  { term: 'VFL', full: 'Visual Fault Locator', short: 'Fiber tool that shines visible light to find breaks or bad bends.' },
  { term: 'VLAN', full: 'Virtual Local Area Network', short: 'Logical split that creates a separate broadcast domain.' },
  { term: 'VPC', full: 'Virtual Private Cloud', short: 'Isolated cloud network with its own address space and routing.' },
  { term: 'VPN', full: 'Virtual Private Network', short: 'Encrypted tunnel over an untrusted network.' },
  { term: 'VRRP', full: 'Virtual Router Redundancy Protocol', short: 'Open standard FHRP using master and backup routers.' },
  { term: 'VTP', full: 'VLAN Trunking Protocol', short: 'Cisco protocol for sharing VLAN information across switches.' },
  { term: 'WAN', full: 'Wide Area Network', short: 'Network that spans large distances or connects sites.' },
  { term: 'WEP', full: 'Wired Equivalent Privacy', short: 'Old broken Wi-Fi security protocol. Do not use it.' },
  { term: 'WPA2', full: 'Wi-Fi Protected Access 2', short: 'Common Wi-Fi security standard that replaced weak WEP.' },
  { term: 'WPA3', full: 'Wi-Fi Protected Access 3', short: 'Newer Wi-Fi security standard with stronger protections.' },
  { term: 'ZTNA', full: 'Zero Trust Network Access', short: 'Access model that verifies every request instead of trusting the network.' },
  { term: '802.1Q', full: 'IEEE 802.1Q', short: 'VLAN tagging standard used on trunk links.' },
  { term: '802.1X', full: 'IEEE 802.1X', short: 'Port-based network access control, often backed by RADIUS.' },
  { term: '802.11', full: 'IEEE 802.11', short: 'Family of Wi-Fi standards.' },
  { term: '802.11ac', full: 'IEEE 802.11ac', short: 'Wi-Fi 5 standard, mainly 5 GHz.' },
  { term: '802.11ax', full: 'IEEE 802.11ax', short: 'Wi-Fi 6 standard, built for higher efficiency and dense client areas.' },
  { term: '802.3af', full: 'IEEE 802.3af', short: 'PoE standard.' },
];
