export interface Protocol {
  abbr: string;
  fullName: string;
  fullNameAccept: string[];
  description: string;
  port: string;
  transport: string;
  descKeywords: string[][];
  why: string;
}

export const PROTOCOLS: Protocol[] = [
  {
    abbr: 'SSH',
    fullName: 'Secure Shell',
    fullNameAccept: ['secure shell'],
    description: 'Securely access and execute commands on a remote machine',
    port: '22',
    transport: 'TCP',
    descKeywords: [['remote'], ['secure', 'securely'], ['command', 'execute']],
    why: 'A sysadmin manages a Linux server from home over an encrypted terminal session. TCP because every command must arrive in order; a dropped character breaks the session.',
  },
  {
    abbr: 'FTP',
    fullName: 'File Transfer Protocol',
    fullNameAccept: ['file transfer protocol'],
    description: 'Transfer files between client and server',
    port: '20/21',
    transport: 'TCP',
    descKeywords: [['file'], ['transfer']],
    why: 'A web developer uploads site files to a hosting server. TCP because the complete file must transfer without missing bytes.',
  },
  {
    abbr: 'Telnet',
    fullName: 'Telnet',
    fullNameAccept: ['telnet'],
    description: 'Insecure remote login, sends data as plaintext',
    port: '23',
    transport: 'TCP',
    descKeywords: [['remote'], ['login', 'access'], ['insecure', 'plaintext', 'plain text']],
    why: 'Legacy routers were configured this way before SSH existed. TCP but sends everything as plaintext, so anyone on the network can read your password.',
  },
  {
    abbr: 'SMTP',
    fullName: 'Simple Mail Transfer Protocol',
    fullNameAccept: ['simple mail transfer protocol'],
    description: 'Send email between mail servers',
    port: '25',
    transport: 'TCP',
    descKeywords: [['email', 'mail'], ['send', 'transfer']],
    why: "Gmail's servers use this to forward your sent email to the recipient's mail server. TCP because a half-delivered email is useless.",
  },
  {
    abbr: 'DNS',
    fullName: 'Domain Name System',
    fullNameAccept: ['domain name system'],
    description: 'Resolve hostnames to IP addresses',
    port: '53',
    transport: 'TCP and UDP',
    descKeywords: [['hostname', 'name', 'domain'], ['ip', 'address', 'resolv']],
    why: 'When you type google.com, your device asks a DNS server for the IP address. UDP because it is a tiny one-question one-answer exchange; the overhead of a TCP handshake would slow every single website load.',
  },
  {
    abbr: 'DHCP',
    fullName: 'Dynamic Host Configuration Protocol',
    fullNameAccept: ['dynamic host configuration protocol'],
    description: 'Automatically assign IP addresses to devices',
    port: '67/68',
    transport: 'UDP',
    descKeywords: [['ip', 'address'], ['assign', 'automatic', 'dynamic', 'distribut', 'provide', 'give', 'hand']],
    why: 'Your phone connects to hotel WiFi and gets an IP address within seconds. UDP because the device has no IP yet and cannot establish a TCP connection, so it broadcasts to the whole network hoping a server responds.',
  },
  {
    abbr: 'TFTP',
    fullName: 'Trivial File Transfer Protocol',
    fullNameAccept: ['trivial file transfer protocol'],
    description: 'Lightweight file transfer with no authentication',
    port: '69',
    transport: 'UDP',
    descKeywords: [['file'], ['transfer'], ['auth', 'lightweight', 'trivial']],
    why: 'A network switch downloads its firmware from a local server during boot. UDP by design: TFTP is intentionally simple with no authentication or error correction.',
  },
  {
    abbr: 'HTTP',
    fullName: 'Hypertext Transfer Protocol',
    fullNameAccept: ['hypertext transfer protocol'],
    description: 'Transfer web pages between browser and server',
    port: '80',
    transport: 'TCP',
    descKeywords: [['web'], ['browser', 'transfer', 'page', 'hypertext']],
    why: 'A browser loads a webpage over an unencrypted connection. TCP because every HTML tag, image, and script must arrive complete.',
  },
  {
    abbr: 'POP3',
    fullName: 'Post Office Protocol version 3',
    fullNameAccept: [
      'post office protocol version 3',
      'post office protocol v3',
      'post office protocol 3',
      'post office protocol version three',
    ],
    description: 'Download email from a server to a local client',
    port: '110',
    transport: 'TCP',
    descKeywords: [['email', 'mail'], ['download', 'local', 'retriev']],
    why: 'Outlook downloads your inbox to your laptop and removes it from the server. TCP because missing emails would be a serious problem.',
  },
  {
    abbr: 'NTP',
    fullName: 'Network Time Protocol',
    fullNameAccept: ['network time protocol'],
    description: 'Synchronize clocks across network devices',
    port: '123',
    transport: 'UDP',
    descKeywords: [['time', 'clock'], ['sync']],
    why: 'Your laptop syncs its clock to an internet time server. UDP because it is a tiny timestamp exchange; reliability matters less than speed for clock sync.',
  },
  {
    abbr: 'IMAP',
    fullName: 'Internet Message Access Protocol',
    fullNameAccept: ['internet message access protocol'],
    description: 'Access and manage email stored on a mail server',
    port: '143',
    transport: 'TCP',
    descKeywords: [['email', 'mail'], ['server'], ['access', 'manage', 'stor', 'stay', 'remain']],
    why: 'You read the same email on your phone and laptop and both stay in sync with the server. TCP because mail state must be consistent across all devices.',
  },
  {
    abbr: 'SNMP',
    fullName: 'Simple Network Management Protocol',
    fullNameAccept: ['simple network management protocol'],
    description: 'Monitor and manage network devices',
    port: '161/162',
    transport: 'UDP',
    descKeywords: [['network'], ['monitor', 'manage']],
    why: 'A network dashboard shows CPU usage and uptime for 50 routers simultaneously. UDP because monitoring polls are frequent and small; a missed poll just means one missing data point, not a crisis.',
  },
  {
    abbr: 'LDAP',
    fullName: 'Lightweight Directory Access Protocol',
    fullNameAccept: ['lightweight directory access protocol'],
    description: 'Query and manage directory services like Active Directory',
    port: '389',
    transport: 'TCP and UDP',
    descKeywords: [['directory'], ['query', 'manage']],
    why: 'When you log into your work computer, Windows checks Active Directory to verify your username and password. TCP and UDP both; TCP for large directory queries, UDP for simple lookups.',
  },
  {
    abbr: 'HTTPS',
    fullName: 'Hypertext Transfer Protocol Secure',
    fullNameAccept: ['hypertext transfer protocol secure'],
    description: 'Encrypted web traffic using TLS',
    port: '443',
    transport: 'TCP',
    descKeywords: [['encrypt', 'tls', 'secure'], ['web']],
    why: 'Online banking encrypts your session so nobody on the same WiFi can see your account details. TCP because every byte of a financial transaction must arrive intact.',
  },
  {
    abbr: 'SMB',
    fullName: 'Server Message Block',
    fullNameAccept: ['server message block'],
    description: 'Share files and printers across a network',
    port: '445',
    transport: 'TCP',
    descKeywords: [['file', 'printer', 'share'], ['network']],
    why: 'A Windows user maps a Z: drive to access shared company files on a server. TCP because file transfers must be complete and ordered.',
  },
  {
    abbr: 'RDP',
    fullName: 'Remote Desktop Protocol',
    fullNameAccept: ['remote desktop protocol'],
    description: 'Graphical remote desktop access to a Windows machine',
    port: '3389',
    transport: 'TCP',
    descKeywords: [['remote', 'desktop'], ['graphical', 'windows']],
    why: 'An IT tech takes remote control of a user\'s Windows desktop to fix a software issue. TCP because every screen update and mouse click must arrive in sequence.',
  },
];
